server:
  port: 3344

# git配置
spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/getao-IT/springcloud-source-code.git #GitHub上面的git仓库名字
          ####搜索目录
          search-paths:
            - springcloud-config
      ####读取分支
      label: master

# 服务注册进eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  # 服务实例信息
  instance:
    instance-id: configcenter3344
    prefer-ip-address: true # 访问路径显示ip端口信息
    lease-renewal-interval-in-seconds: 30 # 发送心跳间隔
    lease-expiration-duration-in-seconds: 90 # 距离最后一次发送心跳后，超过这个时间，服务将被删除
