server:
  port: 8006

spring:
  application:
    name: cloud-payment-service
  cloud:
    consul:
      # 服务器consul中服务名称
      discovery:
        hostname: 127.0.0.1
        service-name: ${spring.application.name}
      # 本机consul地址
      host: localhost
      port: 8500
